version: '3.8'

services:
  react-app-client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react_dev
    ports:
      - "5175:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - shared-network-uniselec
    restart: unless-stopped
    command: yarn dev --host


networks:
  shared-network-uniselec:
    external: true